[workspace]
resolver = "2"

members = ["*/*/rust*"]

[workspace.dependencies]
itertools = "0.13.0"
rayon = "1.10.0"
rstest = "0.23.0"
ndarray = "0.16.1"
pathfinding = "4.11.0"
petgraph = "0.6.5"
divan = "0.1.16"

