[package]
name = "rust05_24"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
# divan = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "main"
harness = false