[package]
name = "rust20_24"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-hash.workspace = true
rayon.workspace = true
pathfinding.workspace = true
itertools.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "main"
harness = false