[package]
name = "rust02_24"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = { workspace = true }
itertools = { workspace = true }

[dev-dependencies]
divan = { workspace = true }

[[bench]]
name = "main"
harness = false