[package]
name = "rust07_24"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "main"
harness = false