[package]
name = "rust11_24"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = { workspace = true }
rayon = { workspace = true }
rustc-hash = "2.1.0"

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "main"
harness = false