[package]
name = "rust11_24"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools.workspace = true
rayon.workspace = true
rustc-hash.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "main"
harness = false